services:
  - type: web
    plan: free
    name: grocery-bud-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangocrud.asgi:application -k uvicorn.workers.UvicornWorker"
